# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# tic documentation to get started: https://ropenscilabs.github.io/tic/
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
- R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
- R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
- R -q -e 'remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
- R -q -e 'tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:
before_install:
  - sudo apt-get install -y libudunits2-dev
addons:
  apt:
    update: true

# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#services
services:

notifications:
  slack:
    secure: CBOVW27VgULRCeD/BNHjy05HB8az2udURykEGVQggRunxbXZlvZYxWVAgatmMhy3lKAR0pXux/gg/bp0RbZ8t+d3CalBUTYgeYvl/6HGpB+eqwcjZUOaQVNg1qq4rooiMjJvsKzGB49hWuYAsCipknGo+KezjiT7DiKyreSBxahb0OjCu/CQf4bT9UkiJjIf9AxPFtRIdbWzswJJrJs9lE2mP9uetA+Cy9R/scVhgj8ZpBneeTIuE3Wm3iC26WrXe3WxB7W56UbI98H3/F+HKfIT6z0G/eBP2v4Dv4FbeXEzPcBUD5hpvFWlK+ueyEML7gWGmQpXOxhuWvAJAJtF/9Htr0VXVTEp876e0owKopCFfY6nroMR4/Cyzu5V5v6CxUp+PctVJImkc3b9zrG1ktDnT6s8HRSR+i+l6qWTC9CXKRx954lgYPSrkWJss+VkxIQ0iFKd4iEhhJvP7lQkc/L5fl62Di6++crBrStEujcIKjf5Cy6pZ9vCYZNjCceqzhysaAz+OsFPyF/2Fe6bCuCJn+UMSN1/C1DlpxHdh+WFqtFMiJjkY6q+F6EecomUYTa39yzX7o/RUxl++c1hchun1s0koc7VFE02ipV96CX+R+L61IrQoBxlDKcr5LASWg8m6Tq7McoqlK+E28M0k0I3NeSm5P0EqIx6hUthzpw=
