---
title: "FCDS 2018 Dataset Overview"
# author: '`r Sys.info()["effective_user"]`'
# date: '`r strftime(Sys.time(), "%A, %b %d, %Y")`'
mainfont: 'Source Serif Pro'
monofont: 'Source Code Pro'
output:
  bulma::bulma_document: 
    toc: true
  rmarkdown::html_document:
    df_print: kable
    standalone: true
  pdf_document: 
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, cache = FALSE,
  warning = FALSE, message = FALSE,
  fig.width = 10, fig.height = 7, 
  fig.showtext = TRUE # for the fancy fonts, disable if not needed
)
```

```{css global-css, echo=FALSE}
img {
  margin: 0;
  padding: 0;
  max-width: 100%;
}
```

```{r library, include=FALSE}
library(tidyverse)
library(glue)

# Use the grkmisc theme
theme_set(
  grkmisc::theme_grk(
    base_family = "Source Sans Pro",
    axis_text_family = "Source Code Pro",
    axis_title_family = "Source Sans Pro",
    default_geom_font = "Source Sans Pro",
    use_showtext = TRUE
  ) + 
    theme(panel.grid.minor = element_blank())
)
```

```{r load, include=FALSE}
# Load Data
fcds <- readRDS(here::here("data", "stat_dataset_2018_clean.rds"))
```

<!-- Start Document Here -->

<!-- ##  {.tabset .tabset-pills} -->

\scriptsize

```{r, results = "asis"}
summary_plot <- function(.data, var) {
  var <- rlang::sym(var)
  var_name <- rlang::quo_name(var)
  var_class <- if (str_detect(var_name, "date")) "date" else class(pull(.data, !!var))
  var_vals <- pull(.data, !!var) %>% unique()
  if (var_class == "character" & length(var_vals) > 20) {
    var_class <- "character+"
  }
  truncate_var_vals <- var_class == "character" && any(nchar(var_vals[!is.na(var_vals)]) > 80)
  if (truncate_var_vals) {
    var_vals_trunc <- var_vals
    var_vals_trunc[nchar(var_vals) > 80] <- var_vals_trunc[nchar(var_vals) > 80] %>% 
      substr(1, 77) %>% 
      paste0("...")
    var_vals_trunc <- str_wrap(var_vals_trunc, 40)
    var_vals <- set_names(var_vals_trunc, var_vals)
  }
  g <- switch(
    var_class,
    "date" = {
      .data %>% 
        count(!!var) %>% 
        ggplot() + aes(!!var, n, group = 1) + geom_line() + geom_point()
    }, 
    "character" = {
      .data %>% 
        count(!!var) %>%
        ungroup() %>% 
        {
          if (truncate_var_vals) mutate(
            ., !!var_name := var_vals[!!var]
          ) else .
        } %>% 
        mutate(
          !!var_name := grkmisc::if_na(!!var, then = "Missing"),
          n_label = grkmisc::pretty_num(n),
          !!var_name := fct_relabel(!!var, ~paste0(!!var, " (", n_label, ")")),
          !!var_name := fct_reorder(!!var, n)
        ) %>% 
        ggplot() + aes(!!var, n) %>% geom_col() + coord_flip() + labs(x = "Frequency")
    }, "character+" = {
      .data %>% 
        count(!!var) %>% 
        arrange(desc(n), !!var)
    }, 
    "integer" = ,
    "numeric" = {
      ggplot(.data) +
        aes(!!var) +
        geom_histogram()
    }
  )
  cat("\n\n###", var_name, "\n\n")
  if (inherits(g, "ggplot")) g + ggtitle(var_name) else {
    cat(glue("\n\n`{var_name}` contains {length(var_vals)} unique values, showing the {min(length(var_vals), 25)} most prevalent.\n"))
    cat("\n\n")
    cat(capture.output(knitr::kable(head(g, n = 25))), sep = "\n")
  }
}

fcds %>%
  colnames() %>%
  walk(~ print(summary_plot(., .data = fcds)))
```
